FROM node:22-alpine AS build

WORKDIR /app

COPY . /app
RUN npm install
RUN npm run build

FROM nginx:alpine AS prod

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /usr/share/nginx/html
COPY --from=build /app/dist/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
